language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tagging
  - docker tag udagram-api-feed patrickha55/udagram-api-feed:v2
  - docker tag udagram-api-user patrickha55/udagram-api-user:v2
  - docker tag udagram-frontend patrickha55/udagram-frontend:v3
  - docker tag reverseproxy patrickha55/reverseproxy:v2

after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push patrickha55/udagram-api-feed:v2
  - docker push patrickha55/udagram-api-user:v2
  - docker push patrickha55/udagram-frontend:v3
  - docker push patrickha55/reverseproxy:v2