apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-api-feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-feed
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50