apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: patrickha55/udagram-frontend:v2
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
        ports:
        - containerPort: 8100
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret

